# simple container for running/testing karadav
# doesn't include libgd or imagemagick for thumbnail generation
services:
  karadav:
    image: php:8.3-cli
    container_name: karadav
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: php -S 0.0.0.0:8080 -t /app/www /app/www/_router.php
